### ISSUE TITLE
Errno::EISDIR when attempting to use svgr command

### ISSUE THREAD

**Issue by djberg96** [nassredean/svgr#3]
Ruby 3.2.2
OS X Ventura
svgr 0.1.4

I'm trying to use svgr to create a grid of some existing svg files that I have at https://github.com/djberg96/DansGameBits/tree/main/Blocks/WellingtonsWar/Spanish. I cd'ed to that directory and ran the following command to create a 4x7 grid:

`>svgr arrange:grid . 4 7`

(I also tried an absolute path instead of ".", same result)

However, I get the following error:

```

/Users/dberger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/svgr-0.1.4/lib/svgr/arrange/grid.rb:78:in `read': Is a directory @ io_fread - . (Errno::EISDIR)
	from /Users/dberger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/svgr-0.1.4/lib/svgr/arrange/grid.rb:78:in `read_svg_file'
	from /Users/dberger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/svgr-0.1.4/lib/svgr/arrange/grid.rb:62:in `block in start'
	from /Users/dberger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/svgr-0.1.4/lib/svgr/arrange/grid.rb:61:in `each'
	from /Users/dberger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/svgr-0.1.4/lib/svgr/arrange/grid.rb:61:in `flat_map'
	from /Users/dberger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/svgr-0.1.4/lib/svgr/arrange/grid.rb:61:in `start'
	from /Users/dberger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/svgr-0.1.4/bin/svgr:13:in `block in start'
	from /Users/dberger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/svgr-0.1.4/bin/svgr:44:in `start'
	from /Users/dberger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/svgr-0.1.4/bin/svgr:52:in `<top (required)>'
	from /Users/dberger/.rbenv/versions/3.2.2/bin/svgr:25:in `load'
	from /Users/dberger/.rbenv/versions/3.2.2/bin/svgr:25:in `<main>'
```

**Comment by djberg96** [comment]
Looks like a dead project, closing.
